name: C++ CI

on:
  push:
    branches:
      - dev
      - 'feat-*'
      - 'bug-*'
      - 'refactor-*'
      - 'docs-*'
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ ninja-build

    - name: Configure project
      run: cmake -B build -G Ninja -DCMAKE_CXX_STANDARD=20

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build --output-on-failure
